namespace Gamepackage
{

    // Important - After release add new entries to the end of this file or you will break all existing save files

    public enum UniqueIdentifier
    {
        EFFECT_POISON_IMMUNITY,
        EFFECT_TRAVERSE_STAIRCASE,
        EFFECT_LUCKY_COIN_LIFE_SAVE,
        EFFECT_WEAK_POISON,
        EFFECT_STRENGTH_OF_GIANTS,
        EFFECT_APPLIED_WEAK_POISON,
        EFFECT_APPLIED_STRONG_POISON,
        EFFECT_APPLIED_POISON_IMMUNITY,
        EFFECT_STRONG_POISON,
        BEHAVIOUR_STANDARD,
        BEHAVIOUR_PLAYER,
        ENTITY_PONCY,
        ENTITY_MASLOW,
        ENTITY_GIANT_BEE,
        ENTITY_QUEEN_BEE,
        ENTITY_STAIRS_UP,
        ENTITY_STAIRS_DOWN,
        ENTITY_GROUND_DROP,
        ENCOUNTER_BEE_SWARM,
        VIEW_MARKER_RED,
        VIEW_MARKER_BLUE,
        VIEW_MARKER_YELLOW,
        VIEW_MARKER_GREEN,
        VIEW_STAIRCASE_UP,
        VIEW_STAIRCASE_DOWN,
        VIEW_CORPSE,
        TRIGGER_TRAVERSE_STAIRCASE,
        ITEM_ANTIDOTE,
        ITEM_LONGSWORD,
        ITEM_LUCKY_COIN,
        ITEM_ARROW,
        ITEM_APPEARANCE_GREEN_POTION,
        ITEM_APPEARANCE_LUCKY_COIN,
        ITEM_APPEARANCE_LONGSWORD,
        ITEM_APPEARANCE_ARROW,
        TILESET_STONE,
    }
}
